update deps
Jasperav/Catalytic pull request #48
Opened 2024-10-20 19:56 UTC by gabriel-v

Scylla v0.14 and all of the others

Added new dev dependency for running all the tests that were starting with "truncate table" serially instead of in parallel ( i got some errors until i figured out to run with --test-thread=1 )

2024-10-21 07:24 UTC, Jasperav requested changes
Thanks for the PR! If you made the changes to the dependency and bump the Cargo.toml, I will publish the new version.

2024-10-21 07:24 UTC, Jasperav commented on Cargo.toml
> +scylla = "0.14.0" # This crate is specifically build for this version
This specific version dependency is fine, for the others, please remove the patch version :) so x.y and not x.y.z

2024-10-21 10:07 UTC, gabriel-v commented
ok

bumped workspace version 0.2.0, there are breaking changes:
- `select_paged` has different argument type
- the "Cursor" pub typedef was not used anymore

2024-10-21 13:54 UTC, Jasperav commented
@gabriel-v LGTM, do you know why this error occurs on the CI? https://github.com/Jasperav/Catalytic/actions/runs/11437836428/job/31829718889?pr=48. If the CI is ok, I will publish the new version!

2024-10-21 17:26 UTC, gabriel-v commented
here you go

https://github.com/gabriel-v/Catalytic/actions/runs/11445259484

errors in order:
- cargo lock version = 4 was from my local nightly compiler, when switched to stable, it now outputs version = 3
- muted some clippy errors about comment string formatting, unrelated to patch
- muted clippy error on dead code (Field::attribute, undocumented, for macro?) - plz review
- removed "... and type is not null" from materialized view example - this errors (as type is not PK) in scylla >5.4.X, 6.x but not scylla 5.2.X nor cassandra 3.11
- updated CI compiler toolchain to the newer one i had locally, since the compiler error text tests depend closely on compiler version (different structs implementing missing trait get printed)

2024-10-22 06:13 UTC, merged

2024-10-22 06:19 UTC, Jasperav commented
Thanks a lot @gabriel-v, I published the changes!